### ISSUE TITLE
Belfagor2005 changes not working

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/XMLTV-Import#105]
@belfagor2005
Unless I missed copying a file over, the branch of the plugin with your changes does not work for me.  I am using a manual download, not a timed download. @jbleyel has recommended I upload my bouquets for you to look at on a forum. There is no issue with the python3 branch.

Your changes on PLi work, but they have broken the log file.

[bouquets_backup_2.zip](https://github.com/user-attachments/files/19573026/bouquets_backup_2.zip)

**Comment by Belfagor2005** [comment]
Hi and thanks for the feedback,
I tried on atv and pli and everything works but I don't have astra provider.
The sources are updated in this git,

We agreed with @jbleyel  that you were doing some tests first, I gave a hand and tried to do my best, the last pulls are missing, but I attach the complete zip here, obviously, don't use the import. But maybe @jbleyel has made other updates.
Let's try to coordinate and if there are changes we can all do them.

https://github.com/oe-alliance/XMLTV-Import/compare/master...Belfagor2005:XMLTV-Import:master

Mirror on  oealliance . 
https://github.com/Belfagor2005/epgimportgz/tree/gh-pages

My source worked
https://github.com/[Belfagor2005/EPGimport-Sources](https://github.com/Belfagor2005/EPGimport-Sources)

Regards

**Comment by jbleyel** [comment]
Merge done

https://github.com/oe-alliance/XMLTV-Import/commit/a7fb8ad994648c6229db9a1d2e5fb8c49f5c5843

**Comment by AbuBaniaz** [comment]
That is working on a manual import now.  Thanks. (I have not changed source files and wont be for my tests.) 

However, the days picker is not working.  Please note I have reworded some options if you are going to submit a pull request. 
I also think Doglover's source files should be the default.

**Comment by jbleyel** [comment]
What’s the problem with the day picker?

**Comment by AbuBaniaz** [comment]
When you press OK, you are meant to be able to select on which days to schedule the import. Nothing happens when you press OK. 

(Note: Following the changes, PLI version now crashes when you press OK)

**Comment by jbleyel** [comment]
fixed

**Comment by Belfagor2005** [comment]
Any changes or improvements are always welcome, you are the masters. I just put some ideas.

I believe only users can test which sources to use.
I spent days testing them, I don't have astra, but they wrote to me that everything works, and I will keep my sources updated on my git.
Everyone can choose what and how to do it.

Regards

**Comment by AbuBaniaz** [comment]
In my opinion, updating the source files should not remove existing options and other providers. The source files tells the receiver which servers to get the channel mapping files and EPG data. It must not remove xml files created by other plugins or transferred by the user. It removes the EPG providers created by BMX

The EPG data the user wants to obtain is still the same. Any new sources that the updated sources provides will naturally be unselected. 

I two pervious other posts, you have mixed up (i.e confused/conflated) sources and EPG. They are two different things!

**Comment by AbuBaniaz** [comment]
A file was sent to me by jbleyel which does not remove settings. His commit is here on my fork: https://github.com/AbuBaniaz/XMLTV-Import-OEA/commit/db123501e80287f6b4f80cfa1b45f6c0ed2c376d

 I dont think he will continue with being piggy in the middle.

I suppose the middle ground is an option to remove existing xml files and configured source options. Maybe all those options on a separate screen.

**Comment by Belfagor2005** [comment]
it was created to import from git.

if you think it is appropriate to change it, go ahead.
mine was a bit different if I'm not mistaken

only this missing

`	for root, dirs, files in walk(extracted_dir):
		if '.github' in dirs:
			rmtree(join(root, '.github'))`

**Comment by jbleyel** [comment]
I have completely changed the code to support only the root folder and only xml files in the tar file.
All other files and folders will be ignored.
Maybe I have missed something.

**Comment by AbuBaniaz** [comment]
Can we find a way to mark the servers that do not want multiple downloads a day?

**Comment by Belfagor2005** [comment]
explain to me better, if I can do it or we find a way, there is a way of success. But I want to understand better what it is about my friend.

**Comment by AbuBaniaz** [comment]
Sorry about late response. Firstly, I must re-emphasise that source files and EPG data are two different things. It seems that this does not seem to be realised.

The Rytec EPG used by most E2 users is uploaded once a day. Downloading unchanged data every 3 hours is pointless. The EPG servers that host EPG data the E2 community uses are provided free of charge. If they become overwhelmed by the sheer number of EPG downloads, the people who do this will end up ceasing the free service they provide. One recently did just that. 

We obviously need to move with the times as more people use their E2 receivers for IPTV. As well as some IPTV servers hosting EPG for only 24 hours and others 12 hours.

Anyway, this is now a moot point as OE-A 5.6 beta branch has now migrated to use your changes.
